app = "supplement"

[build]
  dockerfile = "Dockerfile"

[env]
  TELEGRAM_BOT_TOKEN="dummy_token"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = "start"
  auto_stop_machines = "never" 
