app = "telegram-supplement-bot"

[env]
  TELEGRAM_BOT_TOKEN="7832014763:AAEJBwoFKJDhTXjvLQEt9wkAgtVi-3xgyf0"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = true
